olist_platform:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', '127.0.0.1') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'bright7890') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('DB_NAME', 'ai_analytics_ecommerce') }}"
      schema: public
      threads: 4
  target: dev
